### ISSUE TITLE
[bug][p2] 返回的图片url无法获取图片

### ISSUE THREAD

**Issue by HatsuneMK00** [HatsuneMK00/vue-admin#16]
bug情况：
根据返回的url无法获取到图片
服务端返回的图片url如下图，url本身好像就有点问题
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32505133/113373247-03edd980-939d-11eb-9402-7a1842327fa1.png">

期望情况：
返回可以获取到图片的url

**Comment by harveylo** [comment]
Fixed
