### ISSUE TITLE
[bug][p2] 病例名无法更新

### ISSUE THREAD

**Issue by HatsuneMK00** [HatsuneMK00/vue-admin#17]
bug情况：
病例名更新不符合预期
病例名更新：casename -> casename1
请求url如下图
<img width="388" alt="image" src="https://user-images.githubusercontent.com/32505133/113373818-46fc7c80-939e-11eb-98bc-e847348629bf.png">
返回结果如下图，服务端返回业务代码status=404，数据库中没有更新
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/32505133/113373728-161c4780-939e-11eb-87bf-c0e5e5745119.png">

期望情况：
按照我的理解应该是可以更新的

**Comment by harveylo** [comment]
Fixed
